name: Sync to GitLab

on:
  push:
    branches:
      - master

jobs:
  push_to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch full history
        run: |
          git fetch --unshallow

      - name: Setup SSH and Push to GitLab
        env:
          GITLAB_HOST: git.skni.umcs.pl
          GITLAB_REPO: git@git.skni.umcs.pl:SKNI/syjonizer-2.0.git
          SSH_PRIVATE_KEY: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Debug: Check if the key is added
          echo "Checking private key permissions:"
          ls -l ~/.ssh/id_rsa

          # Ensure known_hosts file is clear and then add GitLab key
          rm -f ~/.ssh/known_hosts
          ssh-keyscan $GITLAB_HOST >> ~/.ssh/known_hosts
          
          # Debug: Check the known_hosts file
          echo "Known Hosts:"
          cat ~/.ssh/known_hosts

          # Remove existing git remote if it exists
          git remote remove gitlab || true
          
          # Add the GitLab remote and push
          git remote add gitlab $GITLAB_REPO
          git push --force gitlab master
