name: Sync to GitLab via Access Token

on:
  push:
    branches:
      - master

jobs:
  push_to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch full history
        run: |
          git fetch --unshallow

      - name: Setup GitLab Access Token and Push to GitLab
        env:
          GITLAB_REPO: https://gitlab-ci-token:${{ secrets.GITLAB_ACCESS_TOKEN }}@git.skni.umcs.pl/SKNI/syjonizer-2.0.git
        run: |
          # Konfiguracja użytkownika (opcjonalnie, jeśli chcesz podać dane użytkownika)
          git config --global user.name "YGithub"
          git config --global user.email "your-email@example.com"

          # Dodaj GitLab remote z HTTPS i tokenem
          git remote set-url origin $GITLAB_REPO

          # Push do GitLab
          git push --force origin master
